data1<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
data1$Date<-strptime(data1$Date,"%d/%m/%Y")
data1$Date<-as.Date(data1$Date)
data_Feb<-subset(data1,Date<="2007-02-02"&Date>="2007-02-01")
data_Feb$Global_active_power<-as.numeric(data_Feb$Global_active_power)
DaTi<-paste(data_Feb$Date,data_Feb$Time)
DaTi<-strptime(DaTi, "%Y-%m-%d %H:%M:%S")
data_Feb$Sub_metering_1<-as.numeric(data_Feb$Sub_metering_1)
data_Feb$Sub_metering_2<-as.numeric(data_Feb$Sub_metering_2)
plot(DaTi,data_Feb$Sub_metering_1,type = "l",xlab="",ylab="Energy sub metering",ylim=c(0,40))
lines(DaTi,data_Feb$Sub_metering_2,col="red")
lines(DaTi,data_Feb$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.copy(png,file="plot3.png", width = 480, height = 480)
dev.off()
