data1<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
data1$Date<-strptime(data1$Date,"%d/%m/%Y")
data1$Date<-as.Date(data1$Date)
data_Feb<-subset(data1,Date<="2007-02-02"&Date>="2007-02-01")
data_Feb$Global_active_power<-as.numeric(data_Feb$Global_active_power)
DaTi<-paste(data_Feb$Date,data_Feb$Time)
DaTi<-strptime(DaTi, "%Y-%m-%d %H:%M:%S")
plot(DaTi,data_Feb$Global_active_power,type = "l",xlab="",ylab="Global Active Power (kilowatts)")
dev.copy(png,file="plot2.png", width = 480, height = 480)
dev.off()
